name: Java CI with Gradle
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'OpenJDK'

      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run test with Gradle Wrapper
        run: ./gradlew test
